spring.datasource.url=jdbc:postgresql://localhost:5432/vetTriageDb
spring.datasource.username=postgres
spring.datasource.password=alicci
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false

app.jwt.secret=VetTriageSecretKeyForJWTTokenGenerationMustBe256BitsLongOrMore
app.jwt.expiration-ms=28800000

server.port=8080
